### ISSUE TITLE
USER STORY 1A: Navigation Menu

### ISSUE THREAD

**Issue by cardan22** [cardan22/thepastryhub#1]
As a **site visitor**, I can **access a navigation menu**, so I can **easily explore the website**.

**Tasks**
- [x] Implement a responsive navigation bar
- [x] Ensure navigation links lead to the correct pages

**Acceptance Criteria**
- [x] The navigation menu is responsive on all devices.
- [x] Users can easily navigate the website.
