### ISSUE TITLE
USER STORY 3B: Recipe Editing/Deletion 

### ISSUE THREAD

**Issue by cardan22** [cardan22/thepastryhub#10]
As a **site user**, I can **edit and delete my recipes** so that **I can make adjustments or remove recipes as necessary**.

**Tasks**
- [x] Allow registered users to edit/delete their recipes.
- [x] Implement user-friendly UX/UI.

**Acceptance Criteria**
- [x] Users can edit or delete their recipes.
- [x] The user interface provides a user-friendly experience.
