### ISSUE TITLE
USER STORY 3C: Like/unlike Recipes 

### ISSUE THREAD

**Issue by cardan22** [cardan22/thepastryhub#11]
As a **user**, I can **like recipes that I enjoy**, so that **I can bookmark my favorite recipes**.

**Tasks**
- [x] Create "Like" button for recipes, enhancing the UX/UI.

**Acceptance Criteria**
- [x] Registered users can like/unlike recipes.
- [x] The UX/UI of the "Like" button is user-friendly and visually appealing.
