### ISSUE TITLE
USER STORY 3D: Comment Section 

### ISSUE THREAD

**Issue by cardan22** [cardan22/thepastryhub#12]
As a **site user**, I can **comment on recipes** so that **I can share my thoughts or tips with other users**.

**Tasks**
- [ ] Develop a comment section for recipes.
- [ ] Implement user-friendly comment submission and display.

**Acceptance Criteria**
- [ ] Registraded users can post comments on recipes.
- [ ] Comments are displayed with the respective recipes.
