### ISSUE TITLE
USER STORY 4A: Recipe Detail View 

### ISSUE THREAD

**Issue by cardan22** [cardan22/thepastryhub#13]
As a **user**, I can **view the detail of each recipe** so that **I can learn how to bake them**.

**Tasks**
- [x] Create a view and template for displaying recipe details. 
- [x] Implement user-friendly UX/UI.

**Acceptance Criteria**
- [x] Users can access recipe details by clicking on the recipe cards shown on the home page.
- [x] The user interface provides a user-friendly experience.
