### ISSUE TITLE
USER STORY 4B: Personal Recipe View 

### ISSUE THREAD

**Issue by cardan22** [cardan22/thepastryhub#14]
As a **user**, I can **view all my recipe entries** so that **I can easily see and access my own content for editing**.

**Tasks**
- [x] Create user-specific page for viewing own recipes.
- [x] Display recipe entries with status.
- [x] Implement user-friendly UX/UI.

**Acceptance Criteria**
- [x] Create a user-specific page for viewing own recipes.
- [x] Display recipe entries with their respective published/draft status.
- [x] The user interface provides a user-friendly experience.
