### ISSUE TITLE
USER STORY 4C: Liked Recipes view 

### ISSUE THREAD

**Issue by cardan22** [cardan22/thepastryhub#15]
As a **registered user**, I can **see a list of all the recipes I've liked on my profile page** so that **I can easily access and revisit my favorite recipes**.

**Tasks**
- [x] Create profile section for liked recipes.
- [x] Implement a query to retrieve and display the list of liked recipes, including a clickable link to each recipe.

**Acceptance Criteria**
- [x] Users should see a section labeled "Liked Recipes" on their profile page.
- [x] The section displays titles or images of liked recipes.
- [x] Users can click on a recipe title or image to view the respective recipe page.
