### ISSUE TITLE
USER STORY 1B: Relevant Content

### ISSUE THREAD

**Issue by cardan22** [cardan22/thepastryhub#2]
As a **visitor**, I can **find relevant information about the site**, so that **I can decide if I want to create an account**.

**Tasks**
- [x] Include essential information on the homepage.
- [x] Implement user-friendly UX/UI.

**Acceptance Criteria**
- [x] The homepage clearly communicates the site's purpose.
- [x] The user interface provides a user-friendly experience.
