### ISSUE TITLE
USER STORY 1C: Intuitive Design 

### ISSUE THREAD

**Issue by cardan22** [cardan22/thepastryhub#3]
As a **user**, I can **access an intuitive and visually pleasing design** so that **it aligns with the site's purpose**.

**Tasks**
- [x] Design an intuitive user interface.
- [x] Ensure visual elements align with the site's theme and purpose.

**Acceptance Criteria**
- [x] Users find the site easy to navigate and use.
- [x] The design complements the site's purpose.
