### ISSUE TITLE
USER STORY 1D: Page Navigation

### ISSUE THREAD

**Issue by cardan22** [cardan22/thepastryhub#4]
As a **user**, I can **smoothly access different site pages** so that **I can make the most of all the site's features**.

**Tasks**
- [x] Create separate pages for various site functions.
- [x] Implement user-friendly UX/UI.

**Acceptance Criteria**
- [x] Pages are functioning as expected.
- [x] The user interface provides a user-friendly experience.
