### ISSUE TITLE
USER STORY 2B: User Login 

### ISSUE THREAD

**Issue by cardan22** [cardan22/thepastryhub#6]
As a **registered user**, I can **log into my account** so that **I can access my account information**.

**Tasks**
- [x] Design a user login system.
- [x] Implement user-friendly UX/UI.

**Acceptance Criteria**
- [x] Users can access their accounts with provided credentials.
- [x]  The user interface provides a user-friendly experience.
