### ISSUE TITLE
USER STORY 2C: User Logout 

### ISSUE THREAD

**Issue by cardan22** [cardan22/thepastryhub#7]
As a **logged-in user**, I can **log out of my account with ease** so that **I can protect my account information**. 

**Tasks**
- [x] Create a logout option within the user account.
- [x] Implement user-friendly UX/UI.

**Acceptance Criteria**
- [x] Users can log out of their accounts.
- [x] The user interface provides a user-friendly experience.
