### ISSUE TITLE
USER STORY 3A: Add Recipe 

### ISSUE THREAD

**Issue by cardan22** [cardan22/thepastryhub#9]
As a **site user**, I can **add a recipe** so that **I can share it on the site**. 

**Tasks**
- [x] Add a recipe from admin panel.
- [x] Create a form to add a recipe for non-admin users. 
- [x] Implement user-friendly UX/UI.

**Acceptance Criteria**
- [x] Admin user can add a recipe.
- [x] Non-admin user can add a recipe from a form template.
- [x] The user interface provides a user-friendly experience.
